create extension if not exists pgcrypto;

-- Identity: Clerk is the primary identity provider; we store the clerk_user_id.
create table if not exists users (
  clerk_user_id text primary key,
  email text not null,
  tier text not null default 'free' check (tier in ('free','pro','team')),
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  team_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists teams (
  id uuid primary key default gen_random_uuid(),
  owner_clerk_user_id text not null,
  name text not null,
  stripe_customer_id text unique,
  created_at timestamptz not null default now()
);

create table if not exists installs (
  id uuid primary key default gen_random_uuid(),
  clerk_user_id text references users(clerk_user_id),
  team_id uuid references teams(id),
  repo_fingerprint text not null, -- hashed
  host text not null,
  host_mode text not null,
  sz_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists module_events (
  id bigserial primary key,
  install_id uuid references installs(id) on delete cascade,
  event_type text not null,  -- module.installed, module.errored, reconcile.finished, tick, etc.
  module_id text,
  payload jsonb,
  ts timestamptz not null default now()
);

create table if not exists absorb_records (
  id uuid primary key default gen_random_uuid(),
  clerk_user_id text references users(clerk_user_id),
  source_url text not null,
  feature text not null,
  module_id text not null,
  llm_provider text not null,
  tokens_in int, tokens_out int,
  status text not null check (status in ('succeeded','failed')),
  validation_errors jsonb,
  ts timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'users_team_id_fkey'
  ) then
    alter table users
      add constraint users_team_id_fkey foreign key (team_id) references teams(id);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'teams_owner_clerk_user_id_fkey'
  ) then
    alter table teams
      add constraint teams_owner_clerk_user_id_fkey
      foreign key (owner_clerk_user_id) references users(clerk_user_id);
  end if;
end $$;

-- Aggregated views regenerated by a nightly job.
create materialized view if not exists mv_trending_modules as
  select module_id, count(*) as installs_30d
  from module_events where event_type='module.installed' and ts > now() - interval '30 days'
  group by module_id order by installs_30d desc;

create materialized view if not exists mv_capability_bindings as
  select (payload->>'requirer') as requirer, (payload->>'provider') as provider,
         (payload->>'capability') as capability, count(*) as c
  from module_events where event_type='module.reconciled'
  group by 1,2,3 order by c desc;

-- RLS: users see only their own installs/events; public views are unrestricted.
alter table users enable row level security;
alter table installs enable row level security;
alter table module_events enable row level security;
alter table absorb_records enable row level security;

drop policy if exists own_user_row on users;
drop policy if exists own_installs on installs;
drop policy if exists own_events on module_events;
drop policy if exists own_absorbs on absorb_records;

create policy own_user_row on users for select using (clerk_user_id = auth.jwt()->>'sub');
create policy own_installs  on installs  for all using (clerk_user_id = auth.jwt()->>'sub');
create policy own_events    on module_events for select using (
  install_id in (select id from installs where clerk_user_id = auth.jwt()->>'sub'));
create policy own_absorbs   on absorb_records for select using (clerk_user_id = auth.jwt()->>'sub');
